name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: vincd
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Paris
          committer_message: "update metrics"
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
